### ISSUE TITLE
Formatting of charge status labels

### ISSUE THREAD

**Issue by thomasddn** [WJDDesigns/Ultra-Vehicle-Card#165]
Hi!

Would it be possible to use the same "formatting" for battery percentage and range under the charge bar? So it's not about style, but about consistency in how labels and values are presented.

Current situation:
`x% Battery           Range: x unit`

Wanted situation:
`Battery: x%          Range: x unit`

Now I'm using card mod to make it consistent. For anyone interested, here's how I do it:

```css
card_mod:
  style: |
    div.level-text > span {
      display: flex;
      flex-direction: row-reverse;
    }

    div.level-text > span > span:first-of-type::before {
        content: ":";
        margin-right: 5px;
    }

```
