### ISSUE TITLE
Icon grid, what is it for?

### ISSUE THREAD

**Issue by ivik** [WJDDesigns/Ultra-Vehicle-Card#18]
Hi

Not really any issues, more a question. 
What is the icon grid used for? 
I have added 2 sensors and choosen icon. 

But besides the icons nothing else is displayed and when I press the icons nothing really happens. 

Code: 

```
icon_grid_entities:
  - sensor.zaptec_charger_charge_power
  - sensor.erfans_bil_time_charge_complete
custom_icons:
  sensor.zaptec_charger_charge_power: mdi:battery-charging
  sensor.erfans_bil_time_charge_complete: mdi:timer
```

What is the meaning with this, what am I missing? 
Btw, really cool feature, great job!
