### ISSUE TITLE
Charging bar not appearing

### ISSUE THREAD

**Issue by jayscovill** [WJDDesigns/Ultra-Vehicle-Card#203]
I'm not sure what I'm missing and I did have it appearing at one point but I've configured a bar to show the battery level but it's just not appearing at all.  Is it because my car is no longer charging and it hides when not in a charging state?  If that's the case I can't find any bar options that control that.

Also even though I've configured bar for it it doesn't show up in the Customize tab for me to move its location.

```
bars:
  - left_title: Fuel
    left_entity: sensor.sportage_fuel_level
    right_title: Range
    right_entity: sensor.sportage_fuel_range
    bar_color: "var(--primary-color, #3498db)"
    background_color: "var(--card-background-color, #121212)"
    border_color: "var(--divider-color, #555555)"
    left_title_color: "var(--secondary-text-color, #999999)"
    left_text_color: "var(--primary-text-color, #ffffff)"
    right_title_color: "var(--secondary-text-color, #999999)"
    right_text_color: "var(--primary-text-color, #ffffff)"
    limit_indicator_color: "var(--error-color, #ff0000)"
    left_title_size: 14
    left_text_size: 14
    right_title_size: 14
    right_text_size: 14
    bar_size: regular
    bar_radius: round
    show_left: true
    show_right: true
    alignment: space-between
    width: "100"
    use_gradient: false
    gradient_display_mode: value_based
    gradient_stops:
      - id: "1"
        position: 0
        color: "#ff0000"
      - id: "2"
        position: 100
        color: "#00ff00"
    animation_state: ""
    animation_type: none
    action_animation_entity: ""
    action_animation_state: ""
    action_animation: none
    entity: sensor.sportage_fuel_level
  - left_title: Level
    left_entity: sensor.sportage_ev_battery_level
    right_entity: sensor.sportage_ev_range
    bar_color: "var(--primary-color, #3498db)"
    background_color: "var(--card-background-color, #121212)"
    border_color: "var(--divider-color, #555555)"
    left_title_color: "var(--secondary-text-color, #999999)"
    left_text_color: "var(--primary-text-color, #ffffff)"
    right_title_color: "var(--secondary-text-color, #999999)"
    right_text_color: "var(--primary-text-color, #ffffff)"
    limit_indicator_color: "var(--error-color, #ff0000)"
    left_title_size: 14
    left_text_size: 14
    right_title_size: 14
    right_text_size: 14
    bar_size: regular
    bar_radius: round
    show_left: true
    show_right: true
    alignment: space-between
    width: "100"
    use_gradient: true
    gradient_display_mode: value_based
    gradient_stops:
      - id: "1"
        position: 0
        color: "#ff0000"
      - id: "2"
        position: 100
        color: "#00ff00"
    animation_state: "on"
    action_animation_entity: ""
    action_animation_state: ""
    action_animation: none
    entity: sensor.sportage_ev_battery_level
    animation_entity: binary_sensor.sportage_ev_battery_charge
    animation_type: charging-lines
    right_title: Range
```
