### ISSUE TITLE
2.0 Bug: "unknown" entities are shown in active state.

### ISSUE THREAD

**Issue by k-korn** [WJDDesigns/Ultra-Vehicle-Card#207]
On 1.x version, if the entity representing an Icon was in unknown/unavailable state, the icon was displayed in "off/inactive" state.
However, on 2.x (currently, 2.4) icons for entities in unknown state are shown as "Active", which does not feel right.

For example, let's consider a Tesla Sentry Mode icon:

```
icon_rows:
  - id: zo09skk
    width: "100"
    alignment: center
    spacing: small
    icons:
     ...
      - entity: switch.model_3_sentry_mode
        icon_inactive: mdi:checkbox-blank-circle-outline
        icon_active: mdi:circle-slice-8
        color_inactive: var(--secondary-text-color)
        color_active: "#ff0000"
        name_color_inactive: var(--primary-text-color)
        name_color_active: var(--primary-text-color)
        state_color_inactive: var(--secondary-text-color)
        state_color_active: var(--primary-text-color)
        inactive_state: "off"
        active_state: "on"
        inactive_template_mode: false
        active_template_mode: false
        inactive_template: ""
        active_template: ""
        show_state: false
        show_name: false
        show_units: false
        show_icon_active: true
        show_icon_inactive: true
        name: ""
        on_click_action: toggle
        text_position: bottom
        vertical_alignment: center
        text_alignment: center
        icon_size: 24
        text_size: 14
        icon_background: none
        icon_background_color: var(--secondary-background-color)
        container_background: none
        container_background_color: var(--secondary-background-color)
        draggable: true
```

It is displaying gray mdi:checkbox-blank-circle-outline icon when off and bright red mdi:circle-slice-8 (filled circle) when enabled.
In version 1.x, the icon was gray/disabled when the car sleeps (sentry mode not available). Now on 2.x, the icon is displaying "ON" state when the vehicle is offline, which is misleading.
