### ISSUE TITLE
Upgrading from 1.1.0 to any newer version breaks the card

### ISSUE THREAD

**Issue by RandomTask83** [WJDDesigns/Ultra-Vehicle-Card#22]
I'm super excited for the potential of this card!  I installed version 1.1.0 yesterday and added all the sensors... then after upgrading to 1.1.6 I noticed that the battery level and range disappeared.  I then stepped back the versions and found that I had to go all the way back to 1.1.0 to restore the visibility of the battery level and range.

![image](https://github.com/user-attachments/assets/5805b402-7ba3-40f6-a3ad-c0548422222a)

![image](https://github.com/user-attachments/assets/b762fed2-e6d0-4e5c-847a-e931a246492a)

**Comment by WJDDesigns** [comment]
Hey hey first off nice car, second have you tried reinstalling and clearing your cache of the browser?

**Comment by RandomTask83** [comment]
> Hey hey first off nice car, second have you tried reinstalling and clearing your cache of the browser?

Thanks for the quick reply!  Yes, I did try removing and re-installing - is there a more thorough way of removing than through the HACS interface?  

I also did try clearing the cache and the behavior is replicated in different browsers and the iPhone app.  I am also able to restore the battery percentage bar by downgrading back to 1.1.0.

**Comment by domoritz** [comment]
I'm also seeing this behavior where I don't get the new support for PHEVs. 

This is after updating and clearing all the caches and re-creating the card.

<img width="388" alt="Screenshot 2024-08-06 at 17 02 50" src="https://github.com/user-attachments/assets/deb71ba6-968c-4f17-88cb-7917a55699e8">

**Comment by rubin110** [comment]
![image](https://github.com/user-attachments/assets/44aebbc2-ace8-4852-bd8b-368110872abd)

Another one here. 1.1.1 works, 1.1.4 and up similarly doesn't show charge bar or text. I don't see anything in Chrome's console (also there's no message about the front end card getting loaded regardless of version). I don't see any new text fields in the card setup UI for any of the new features you listed in the release notes. I also don't see any charge bar and text html for the card's block.

```yaml
title: Setareh
image_url: /local/teslamodel3transparent.png
vehicle_type: EV
unit_type: mi
level_entity: sensor.tesla_battery_level
range_entity: sensor.tesla_real_world_expected_battery_range_mi
charging_status_entity: binary_sensor.setareh_charging
location_entity: device_tracker.setareh_location_tracker
mileage_entity: sensor.tesla_odometer_mi
show_level: true
show_range: true
show_location: true
show_mileage: true
icon_grid_entities: []
custom_icons: {}
type: custom:ultra-vehicle-card
```

P.S. this is a great card, thanks for making it!
