### ISSUE TITLE
Icon Action "Open URL" does nothing

### ISSUE THREAD

**Issue by NobisIndustries** [WJDDesigns/Ultra-Vehicle-Card#222]
Hi,
Thanks for all your work on this card!

with v2.5.5, I'm trying to configure an icon with the click action "Open URL" as a shortcut to open a specific Android application (my wallbox app) using its app:// URI scheme.
This works correctly with a standard Home Assistant weblink entity:

```
type: entities
entities:
  - type: weblink
    url: app://com.example.wallboxapp
    name: Open Wallbox App
```

Clicking the link above successfully opens the target app via the HA companion app.
However, when configuring an icon in your card like this:
```
icon_rows:
  - icons:
      - entity: sensor.some_sensor
        on_click_action: url
        url: app://com.example.wallboxapp
       ...
```
...clicking the icon currently does nothing. This is also replicated by just using a generic web url instead of trying to open an app.

I noticed that the _handleIconClick function in the card's code currently doesn't include logic to handle the url action type.

Could you please add support for the URL action for icons?

Thanks for considering!
