### ISSUE TITLE
Difference percentage bars don't appear, as they have no selected entity

### ISSUE THREAD

**Issue by x-cubed** [WJDDesigns/Ultra-Vehicle-Card#252]
I have a Zappi charger hooked up to Home Assistant, and an EV that currently isn't linked to Home Assistant. To try to track the progress of the charging, I tried to add a percentage bar to the Ultra Vehicle Card. The Zappi reports `Charge added this session` in kWh, and I know the capacity of the EV's battery in kWh, so I figured that I would use the `Difference (amount/total)` mode of the percentage bar to achieve what I wanted. I created a `Number` helper in Home Assistant to track the EV's battery capacity.

Despite choosing the `Amount Entity` and `Total Entity` options in the configuration window, the percentage bar doesn't show up and the title at the top of the bar configuration states `No entity selected`:
![Image](https://github.com/user-attachments/assets/f75b61b4-5bba-4be9-9773-9132027df9e2)

I did discover a workaround which was to switch back to `Entity (0-100)` mode and choose a value for `Bar Percentage Entity`, then switch back to the `Difference (amount/total)` mode. As soon as a value is selected for `Bar Percentage Entity`, the percentage bar shows up, and it stays there after switching back to `Difference (amount/total)` mode. The `Bar Percentage Entity` field is not shown in `Difference (amount/total)` mode.

Just a little glitch, but would be good to get sorted.

Thanks for all your hard work on this card. I'm really liking all the new customization options.

**Comment by WJDDesigns** [comment]
Can you see if the new beta solves your issues?

**Comment by x-cubed** [comment]
I wasn't able to figure out how to reliably install the beta based on the Manual Installation steps in the Readme, but I did see that you've published `2.6.4`, so I tested again with that.
It still appears to be a problem.

**Comment by x-cubed** [comment]
Here's the YAML for a brand new card with just the percentage bar added (and not currently showing):
```yaml
vehicle_image_type: default
status_image_type: none
layout_type: single
formatted_entities: true
show_location: true
show_mileage: true
show_car_state: true
show_info_icons: true
sections_order:
  - title
  - image
  - info
  - bar_0
bars:
  - left_title: ""
    left_entity: ""
    right_title: ""
    right_entity: ""
    bar_color: "var(--primary-color, #3498db)"
    background_color: "var(--card-background-color, #121212)"
    border_color: "var(--divider-color, #555555)"
    left_title_color: "var(--secondary-text-color, #999999)"
    left_text_color: "var(--primary-text-color, #ffffff)"
    right_title_color: "var(--secondary-text-color, #999999)"
    right_text_color: "var(--primary-text-color, #ffffff)"
    limit_indicator_color: "var(--error-color, #ff0000)"
    left_title_size: 14
    left_text_size: 14
    right_title_size: 14
    right_text_size: 14
    percentage_text_size: 14
    bar_size: regular
    bar_radius: round
    bar_style: flat
    show_left: false
    show_right: false
    show_percentage: false
    percentage_type: difference
    percentage_amount_entity: sensor.myenergi_zappi_10325371_charge_added_session
    percentage_total_entity: input_number.ioniq_battery_capacity
    alignment: space-between
    width: "100"
    use_gradient: false
    gradient_display_mode: value_based
    gradient_stops:
      - id: "1"
        position: 0
        color: "#ff0000"
      - id: "2"
        position: 100
        color: "#00ff00"
    animation_entity: ""
    animation_state: ""
    animation_type: none
    action_animation_entity: ""
    action_animation_state: ""
    action_animation: none
    entity: ""
icon_rows: []
type: custom:ultra-vehicle-card
title: Vehicle Title
title_alignment: center
title_size: 24
show_units: true
vehicle_image_width: 100
action_image_width: 100
```
