### ISSUE TITLE
Icon grid entities does not work

### ISSUE THREAD

**Issue by magune** [WJDDesigns/Ultra-Vehicle-Card#26]
Adding entities to the icon grid does not work, icons are not found:

<img width="336" alt="image" src="https://github.com/user-attachments/assets/cfb9f138-f8ed-426b-a2d9-f2fc0b5b2ddc">

I have added the entities in the icon grid by searching them from inside the card config GUI:

<img width="490" alt="image" src="https://github.com/user-attachments/assets/5c4d8301-0ed6-438d-8354-b0bbacd69d80">

<img width="499" alt="image" src="https://github.com/user-attachments/assets/42f97082-d8a1-414a-bccb-a05b07b18f49">

But after selecting them from the search results dropdown, the features appear color coded as error, and the icons do not show in the card as the top image shows.

Those entities do exist and work otherwise:

<img width="958" alt="image" src="https://github.com/user-attachments/assets/19ca74e3-6115-4628-93af-e41e8baab61a">

**Comment by MartinAirN** [comment]
It seems one of the latest updates broke both the spacing and manually set Icons. The auto use of icons also seems 'faulty'.

**Comment by WJDDesigns** [comment]
In console what version are you running it should show a version tag. You should see a drop down to display more options for each icon bar where you can choose the icons.

**Comment by magune** [comment]
not sure about what the console is or where to find it.

but even if I add the icons to the grid entities, they do not show in the card:

<img width="484" alt="image" src="https://github.com/user-attachments/assets/f7fa3de9-e61b-4f05-a6ce-f3ca8aacdbd1">

<img width="351" alt="image" src="https://github.com/user-attachments/assets/fd45deca-ee05-4167-b66e-8438385c3e46">

I have to confess I just selected icons and entities by complete random for a quick test now, maybe it works if i more carefully select icon and entity?

Additionally the BMW integration uses attributes for detailed data, in addition to the entity on/off. not sure if that causes problems?

<img width="956" alt="image" src="https://github.com/user-attachments/assets/3fed4eb9-94aa-452e-8421-d22812c156a1">

**Comment by magune** [comment]
When I click on the ?-mark icons under the car rendering in the card, the more info dialog shows with correct data
<img width="670" alt="image" src="https://github.com/user-attachments/assets/1801199e-00fc-4693-84cf-8d305621b784">

**Comment by MartinAirN** [comment]
To add, this configuration worked before updating today:

```
      icon_grid_entities:
        - lock.eve_lock_2
        - binary_sensor.eve_hood_2
        - binary_sensor.eve_driver_door_2
        - binary_sensor.eve_passenger_door_2
        - binary_sensor.eve_rear_left_door_2
        - binary_sensor.eve_rear_right_door_2
        - binary_sensor.eve_trunk_2
        - binary_sensor.eve_plugged_in_2
      custom_icons:
        lock.eve_lock_2: mdi:car-key
        binary_sensor.eve_hood_2: mdi:car
        binary_sensor.eve_driver_door_2: mdi:car-door
        binary_sensor.eve_passenger_door_2: mdi:car-door
        binary_sensor.eve_rear_left_door_2: mdi:car-door
        binary_sensor.eve_rear_right_door_2: mdi:car-door
        binary_sensor.eve_trunk_2: mdi:car-back
        binary_sensor.eve_plugged_in_2: mdi:ev-plug-type2`
```

But right now shows as:
![image](https://github.com/user-attachments/assets/32ca3e68-2e9f-418a-b448-5796da9ce8fd)
