### ISSUE TITLE
v2.8.2 is no longer showing icons for my vehicle cards.

### ISSUE THREAD

**Issue by jessevallaro** [WJDDesigns/Ultra-Vehicle-Card#269]
I upgraded yesterday and lost the display of my 2 icons on my cards. The info field is still showing. If I mess around under customize I can get either the info, or the icons to display, but not both.

I then created, from scratch, the same card for one of my vehicles, and the icons don't display either, only the info. 

### Images
**What it looked like previously:**

![Image](https://github.com/user-attachments/assets/f63eb733-7706-4966-97c9-99c46c2c9e1a)

**Original card (v2.8.2):**

![Image](https://github.com/user-attachments/assets/46f01d95-9ac0-487d-838f-8beac988e7fe)

**Newly Created Card (v2.8.2):**

![Image](https://github.com/user-attachments/assets/fa419a64-61cf-4412-a693-4e81d8e5e071)

### Code

**Original card:**
```
vehicle_image_type: upload
status_image_type: none
layout_type: single
formatted_entities: true
show_location: true
show_mileage: true
show_car_state: true
show_info_icons: true
sections_order:
  - title
  - image
  - info_row_e607eo3
  - bar_0
  - icon_row_9b5d9uw
bars: []
icon_rows:
  - id: 9b5d9uw
    width: "100"
    alignment: center
    vertical_alignment: center
    spacing: none
    columns: 0
    icons:
      - entity: sensor.garage_triumph_battery_voltage
        icon_inactive: mdi:car-battery
        icon_active: mdi:car-battery
        color_inactive: var(--secondary-text-color)
        color_active: var(--primary-color)
        name_color_inactive: var(--primary-text-color)
        name_color_active: var(--primary-text-color)
        state_color_inactive: var(--secondary-text-color)
        state_color_active: var(--primary-text-color)
        inactive_state: "off"
        active_state: "on"
        inactive_template_mode: false
        active_template_mode: false
        inactive_template: ""
        active_template: ""
        active_state_text: ""
        inactive_state_text: ""
        show_state: true
        show_name: false
        show_name_active: false
        show_name_inactive: false
        show_state_active: true
        show_state_inactive: true
        show_units: true
        show_icon_active: true
        show_icon_inactive: true
        use_entity_color_for_icon: false
        use_entity_color_for_icon_active: false
        use_entity_color_for_icon_inactive: false
        use_entity_color_for_icon_background: false
        use_entity_color_for_container_background: false
        name: ""
        on_click_action: more-info
        text_position: bottom
        vertical_alignment: center
        text_alignment: center
        icon_size: 24
        text_size: 14
        icon_background: none
        icon_background_color: var(--secondary-background-color)
        container_background: none
        container_background_color: var(--secondary-background-color)
        draggable: true
        action: ""
        service_data: {}
      - entity: sensor.garage_triumph_battery_temperature
        icon_inactive: mdi:thermometer
        icon_active: mdi:thermometer
        color_inactive: var(--secondary-text-color)
        color_active: var(--primary-color)
        name_color_inactive: var(--primary-text-color)
        name_color_active: var(--primary-text-color)
        state_color_inactive: var(--secondary-text-color)
        state_color_active: var(--primary-text-color)
        inactive_state: "off"
        active_state: "on"
        inactive_template_mode: false
        active_template_mode: false
        inactive_template: ""
        active_template: ""
        active_state_text: ""
        inactive_state_text: ""
        show_state: true
        show_name: false
        show_name_active: false
        show_name_inactive: false
        show_state_active: true
        show_state_inactive: true
        show_units: true
        show_icon_active: true
        show_icon_inactive: true
        use_entity_color_for_icon: false
        use_entity_color_for_icon_active: false
        use_entity_color_for_icon_inactive: false
        use_entity_color_for_icon_background: false
        use_entity_color_for_container_background: false
        name: ""
        on_click_action: more-info
        text_position: bottom
        vertical_alignment: center
        text_alignment: center
        icon_size: 24
        text_size: 14
        icon_background: none
        icon_background_color: var(--secondary-background-color)
        container_background: none
        container_background_color: var(--secondary-background-color)
        draggable: true
        action: ""
        service_data: {}
    confirmation_mode: false
type: custom:ultra-vehicle-card
title: Triumph Tiger 1200
title_alignment: center
title_size: 24
show_units: true
vehicle_image_width: 100
action_image_width: 100
location_entity: device_tracker.triumph
vehicle_image: /api/image/serve/03f332fc0c754fc804668eeca4e1bc6a
info_rows:
  - id: e607eo3
    info_entities:
      - id: 5yc47zh
        entity: device_tracker.triumph
        name: ""
        show_icon: true
        icon: mdi:map-marker-outline
        text_color: ""
    alignment: left
    spacing: medium
```

**Newly Created Card:**
```
vehicle_image_type: upload
status_image_type: none
layout_type: single
formatted_entities: true
show_location: true
show_mileage: true
show_car_state: true
show_info_icons: true
sections_order:
  - title
  - image
  - info
  - bar_0
  - icon_row_mv2aax8
bars: []
icon_rows:
  - id: mv2aax8
    width: "100"
    alignment: center
    vertical_alignment: center
    spacing: none
    columns: 0
    icons:
      - entity: sensor.garage_triumph_battery_voltage
        icon_inactive: mdi:car-battery
        icon_active: mdi:car-battery
        color_inactive: var(--secondary-text-color)
        color_active: var(--primary-color)
        name_color_inactive: var(--primary-text-color)
        name_color_active: var(--primary-text-color)
        state_color_inactive: var(--secondary-text-color)
        state_color_active: var(--primary-text-color)
        inactive_state: "off"
        active_state: "on"
        inactive_template_mode: false
        active_template_mode: false
        inactive_template: ""
        active_template: ""
        active_state_text: ""
        inactive_state_text: ""
        show_state: true
        show_name: false
        show_name_active: false
        show_name_inactive: false
        show_state_active: true
        show_state_inactive: true
        show_units: true
        show_icon_active: true
        show_icon_inactive: true
        use_entity_color_for_icon: false
        use_entity_color_for_icon_active: false
        use_entity_color_for_icon_inactive: false
        use_entity_color_for_icon_background: false
        use_entity_color_for_container_background: false
        name: ""
        on_click_action: more-info
        text_position: bottom
        vertical_alignment: center
        text_alignment: center
        icon_size: 24
        text_size: 14
        icon_background: none
        icon_background_color: var(--secondary-background-color)
        container_background: none
        container_background_color: var(--secondary-background-color)
        draggable: true
        action: ""
        service_data: {}
      - entity: sensor.garage_triumph_battery_temperature
        icon_inactive: mdi:thermometer
        icon_active: mdi:thermometer
        color_inactive: var(--secondary-text-color)
        color_active: var(--primary-color)
        name_color_inactive: var(--primary-text-color)
        name_color_active: var(--primary-text-color)
        state_color_inactive: var(--secondary-text-color)
        state_color_active: var(--primary-text-color)
        inactive_state: "off"
        active_state: "on"
        inactive_template_mode: false
        active_template_mode: false
        inactive_template: ""
        active_template: ""
        active_state_text: ""
        inactive_state_text: ""
        show_state: true
        show_name: false
        show_name_active: false
        show_name_inactive: false
        show_state_active: true
        show_state_inactive: true
        show_units: true
        show_icon_active: true
        show_icon_inactive: true
        use_entity_color_for_icon: false
        use_entity_color_for_icon_active: false
        use_entity_color_for_icon_inactive: false
        use_entity_color_for_icon_background: false
        use_entity_color_for_container_background: false
        name: ""
        on_click_action: more-info
        text_position: bottom
        vertical_alignment: center
        text_alignment: center
        icon_size: 24
        text_size: 14
        icon_background: none
        icon_background_color: var(--secondary-background-color)
        container_background: none
        container_background_color: var(--secondary-background-color)
        draggable: true
        action: ""
        service_data: {}
    confirmation_mode: false
type: custom:ultra-vehicle-card
title_alignment: center
title_size: 24
show_units: true
vehicle_image_width: 100
action_image_width: 100
title: Triumph (test)
vehicle_image: /api/image/serve/f758e36f00e69c812368b12dae52ba79
info_rows:
  - id: iqvpan8
    width: "100"
    alignment: center
    vertical_alignment: center
    spacing: medium
    columns: 0
    allow_wrap: false
    info_entities:
      - id: 6flvgly
        entity: device_tracker.triumph
        name: ""
        icon: mdi:radar
        show_icon: true
        show_name: false
        text_size: 14
        name_size: 14
        icon_size: 24
        icon_color: var(--secondary-text-color)
        text_color: var(--primary-text-color)
        on_click_action: more-info
```
