### ISSUE TITLE
Automation from Icon Grid not executed

### ISSUE THREAD

**Issue by fuchsbau123** [WJDDesigns/Ultra-Vehicle-Card#47]
Ultra Vehicle Card Version 1.3.3
Home Assistant: 2024.6.4

Hi,
thanks for your great card. I configured an automation to refresh the data from Kia when pressing an icon.
I can run the automation manually without any issue.
When I click to the icon, the automation is not executed.
I cannot find any message in the debug log.
Any idea?

Here the config:
![image](https://github.com/user-attachments/assets/2eeb88d6-01a3-4763-ba67-281aa84c1148)

Here the the yaml code from the config editor:
```
[..]
icon_grid_entities:
   - sensor.ev9_last_updated_at
icon_interactions:
  sensor.ev9_last_updated_at:
    type: automation
    automation: automation.kia_update
[..]
```
