### ISSUE TITLE
Feature Request - Buttons can call "Actions" \ Services

### ISSUE THREAD

**Issue by Sleeepy2** [WJDDesigns/Ultra-Vehicle-Card#70]
I have a Kia and it looks like it only updates on request. I would like to call an action on a button click to perform an action

```
action: perform-action
  perform_action: kia_uvo.update
  target: {}
  data:
    device_id: mykia
```

FYI, I tried to join the discord but it says Invite Invalid, may be expired...
